services:
  - type: web
    name: fut-team-api
    env: node
    plan: free
    buildCommand: npm install && npm run prisma:generate && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3333
      - key: DATABASE_URL
        fromDatabase:
          name: fut-team-db
          property: connectionString
      - key: JWT_SECRET
        generateValue: true
      - key: CORS_ORIGIN
        value: "*"
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: SENTRY_DSN
        sync: false
      - key: LOGTAIL_SOURCE_TOKEN
        sync: false
